name: "autonoise"
platform: "tensorflow_savedmodel"
max_batch_size: 64

input [
  {
    name: "input_3"
    data_type: TYPE_FP32
    dims: [ 256, 512, 1 ]
  }
]
output [
  {
    name: "conv2d_17"
    data_type: TYPE_FP32
    dims: [ 256, 512, 1 ]
   }
]
